# https://www.gitpod.io/docs/config-gitpod-file
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Pulsar-Broker
    init: |
      tar xfz ./resources/apache-pulsar-2.9.2-bin.tar.gz
      ./apache-pulsar-2.9.2/bin/pulsar standalone

  - name: Working-Directory
    command: |
      until [ -d ./apache-pulsar-2.9.2 ]; do sleep 1; done
      cd ./apache-pulsar-2.9.2
      ./bin/pulsar-admin tenants list
      
ports:
  - port: 8080
    onOpen: ignore
  - port: 4181
    onOpen: ignore
  - port: 3181
    onOpen: ignore
  - port: 6650
    onOpen: ignore
  - port: 2181
    onOpen: ignore

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

vscode:
  extensions:
    - matt-rudge.auto-open-preview-panel