# https://www.gitpod.io/docs/config-gitpod-file
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Pulsar-Broker
    init: |
      curl -O https://archive.apache.org/dist/pulsar/pulsar-2.9.2/apache-pulsar-2.9.2-bin.tar.gz
      tar xfz ./apache-pulsar-2.9.2-bin.tar.gz
      ./apache-pulsar-2.9.2/bin/pulsar standalone

  - name: Working-Directory
    command: |
      until [ -f ./apache-pulsar-2.9.2/bin/pulsar-admin ]; do sleep 1; done
      gp open ./lab1/get-familiar.md
      cd ./apache-pulsar-2.9.2
      
ports:
  - port: 8080
    onOpen: ignore
  - port: 4181
    onOpen: ignore
  - port: 3181
    onOpen: ignore
  - port: 6650
    onOpen: ignore
  - port: 2181
    onOpen: ignore

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
