# https://www.gitpod.io/docs/config-gitpod-file
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install-And-Start-Pulsar
    init: |
      curl -O https://archive.apache.org/dist/pulsar/pulsar-2.9.2/apache-pulsar-2.9.2-bin.tar.gz
      tar xvfz ./apache-pulsar-2.9.2-bin.tar.gz
      ./apache-pulsar-2.9.2/bin/pulsar standalone

  - name: Working-Directory
    command: |
      cd ./apache-pulsar-2.9.2
      ./bin/pulsar-admin tenants list

ports:
  - port: 8080
    onOpen: ignore
  - port: 4181
    onOpen: ignore
  - port: 3181
    onOpen: ignore
  - port: 6650
    onOpen: ignore

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

vscode:
  extensions:
    - hnw.vscode-auto-open-markdown-preview